portfolio:
    resource: "@PortfolioBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


# to redefine url
#fos_user_security_login:
    #path:      /account/login
    #defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }
