portfolio_homepage:
    path:     /
    defaults: { _controller: PortfolioBundle:Portfolio:index }
portfolio_tutoriels:
    path:     /tutoriels
    defaults: { _controller: PortfolioBundle:Portfolio:tutoriels }
portfolio_tutoriel:
    path:     /tutoriel
    defaults: { _controller: PortfolioBundle:Portfolio:tutoriel }
portfolio_articles:
    path:     /articles
    defaults: { _controller: PortfolioBundle:Portfolio:articles }
portfolio_article:
    path:     /article
    defaults: { _controller: PortfolioBundle:Portfolio:article }
portfolio_cv:
    path:     /cv
    defaults: { _controller: PortfolioBundle:Portfolio:cv }
