portfolio_article:
    resource: "@PortfolioBundle/Resources/config/routing/article.yml"
    prefix:   /article

portfolio_homepage:
    path:     /
    defaults: { _controller: PortfolioBundle:Portfolio:index }
portfolio_tutoriels:
    path:     /tutoriels
    defaults: { _controller: PortfolioBundle:Portfolio:tutoriels }
portfolio_tutoriel:
    path:     /tutoriel{id}
    defaults: { _controller: PortfolioBundle:Portfolio:tutoriel }
    requirements:
        id: '\d+'
portfolio_articles:
    path:     /articles
    defaults: { _controller: PortfolioBundle:Portfolio:articles }

portfolio_article_show:
    path:     /article/{id}
    defaults: { _controller: PortfolioBundle:Portfolio:articleshow }
    requirements:
        id: '\d+'

portfolio_cv:
    path:     /cv
    defaults: { _controller: PortfolioBundle:Portfolio:cv }
